added function by each command

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -2,10 +2,27 @@
 
 set -euo pipefail
 
+
+fail() {
+  echo -e "asdf-$TOOL_NAME: $*"
+  exit 1
+}
+
+download_release() {
+  local version filename url
+  version="$1"
+  filename="$2"
+
+  url="https://www.lua.org/ftp/lua-${version}.tar.gz"
+
+  echo "* Downloading $TOOL_NAME release $version..."
+  curl -fsSL -o "$filename" -C - "$url" || fail "Could not download $url"
+}
+
+
+
 current_script_path=${BASH_SOURCE[0]}
 plugin_dir=$(dirname "$(dirname "$current_script_path")")
-
-source "${plugin_dir}/lib/utils.bash"
 
 mkdir -p "$ASDF_DOWNLOAD_PATH"
 
diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -2,6 +2,36 @@
 
 set -euo pipefail
 
+fail() {
+  echo -e "asdf-$TOOL_NAME: $*"
+  exit 1
+}
+
+install_version() {
+  local install_type="$1"
+  local version="$2"
+  local install_path="$3"
+
+  if [ "$install_type" != "version" ]; then
+    fail "asdf-$TOOL_NAME supports release installs only"
+  fi
+
+  (
+    mkdir -p "$install_path"
+    cp -r "$ASDF_DOWNLOAD_PATH"/* "$install_path"
+
+    test -e "$install_path/Makefile" || fail "$install_path/Makefile need to exists."
+
+    make all test
+
+    echo "$TOOL_NAME $version installation was successful!"
+  ) || (
+    rm -rf "$install_path"
+    fail "An error ocurred while installing $TOOL_NAME $version."
+  )
+}
+
+
 current_script_path=${BASH_SOURCE[0]}
 plugin_dir=$(dirname "$(dirname "$current_script_path")")
 
